- name: "copy {{component}} service"
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: "/etc/systemd/system/{{component}}.service"

- name: deamon reload and start
  ansible.builtin.systemd_service:
    daemon_reload: true
  
- name: "start and enable {{component}}"
  ansible.builtin.service:
    name: "{{componenet}}"
    state: restarted
    enables: yes